# Form implementation generated from reading ui file 'ui/all_assignments.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_showAllDialog(object):
    def setupUi(self, showAllDialog):
        showAllDialog.setObjectName("showAllDialog")
        showAllDialog.resize(643, 519)
        self.verticalLayout = QtWidgets.QVBoxLayout(showAllDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=showAllDialog)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.groupBox = QtWidgets.QGroupBox(parent=showAllDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OkButton = QtWidgets.QPushButton(parent=self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.OkButton.setIcon(icon)
        self.OkButton.setIconSize(QtCore.QSize(12, 12))
        self.OkButton.setObjectName("OkButton")
        self.horizontalLayout.addWidget(self.OkButton)
        spacerItem1 = QtWidgets.QSpacerItem(191, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(showAllDialog)
        QtCore.QMetaObject.connectSlotsByName(showAllDialog)

    def retranslateUi(self, showAllDialog):
        _translate = QtCore.QCoreApplication.translate
        showAllDialog.setWindowTitle(_translate("showAllDialog", "All Assignments"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("showAllDialog", "Module Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("showAllDialog", "Assignment Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("showAllDialog", "Due Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("showAllDialog", "Days Left"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("showAllDialog", "Status"))
        self.OkButton.setText(_translate("showAllDialog", "Ok"))
